src/data/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.http.response import HttpResponse
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

import stats

from . import views
from .schema import schema

router = DefaultRouter()
router.register(r"surveys", views.SurveyViewSet)
router.register(r"usersurveys", views.UserSurveyViewSet)
router.register(r"users", views.UserViewSet)

# app_name = "data"  # namespacing has advantages but needs confusing extra config with DRF

urlpatterns = [
    path("api/", include(router.urls)),
    path("api/graphql", views.AsyncGraphQLView.as_view(schema=schema, graphiql=settings.DEBUG)),
]


def broadcast_test(request, pk):
    stats.KAFKA_PRODUCER.send("definitions", str(pk))
    return HttpResponse("hi here")


urlpatterns += [
    # testing
    # path("broadcast/<int:pk>/", broadcast_test, name="broadcast_test"),
    # path("test/", views.OnboardedTemplateView.as_view(template_name="data/test.html"), name="test"),
    # Service Worker template
    path(
        "sw.js",
        TemplateView.as_view(
            template_name="data/sw.js",
            content_type="application/javascript",
        ),
        name="sw",
    ),
    ## API
    path("precache_urls/", views.precache_urls, name="precache_urls"),
    path("user_event/", views.user_event, name="user_event"),
    # Backoffice
    path("", views.HomeView.as_view(template_name="data/home.html"), name="home"),
    ## Data entry
    path(
        "vocab/",
        views.OnboardedTemplateView.as_view(template_name="data/apps/notrobes.html"),
        name="notrobes",
    ),
    path(
        "vocab/list/",
        views.OnboardedTemplateView.as_view(template_name="data/apps/listrobes.html"),
        name="listrobes",
    ),
    ## Active Learning
    path(
        "vocab/review/",
        views.OnboardedTemplateView.as_view(template_name="data/apps/srsrobes.html"),
        name="srsrobes",
    ),
    ## Meta-knowledge management
    # survey.js surveys
    path(
        "survey/<int:survey_id>/",
        views.SurveyView.as_view(template_name="data/apps/survey_detail.html"),
        name="ui_survey_detail",
    ),
    path("surveys/", views.UserSurveysView.as_view(template_name="data/crud/surveys.html"), name="ui_survey_list"),
    # basic cruds
    path(
        "import/create/", views.ImportCreate.as_view(template_name="data/crud/import_create.html"), name="import_create"
    ),
    path("import/list/", views.ImportList.as_view(template_name="data/crud/import_list.html"), name="import_list"),
    path(
        "import/detail/<int:pk>/",
        views.ImportDetail.as_view(template_name="data/crud/import_detail.html"),
        name="import_detail",
    ),
    path(
        "list/create/<int:from_import>/",
        views.ListCreate.as_view(template_name="data/crud/list_create.html"),
        name="list_create",
    ),
    path("list/list/", views.ListList.as_view(template_name="data/crud/list_list.html"), name="list_list"),
    path(
        "list/detail/<int:pk>/",
        views.ListDetail.as_view(template_name="data/crud/list_detail.html"),
        name="list_detail",
    ),
    path(
        "goal/create/<int:from_list>/",
        views.GoalCreate.as_view(template_name="data/crud/goal_create.html"),
        name="goal_create",
    ),
    path("goal/list/", views.GoalList.as_view(template_name="data/crud/goal_list.html"), name="goal_list"),
    path(
        "goal/detail/<int:pk>/",
        views.GoalDetail.as_view(template_name="data/crud/goal_detail.html"),
        name="goal_detail",
    ),
    path(
        "goal/update/<int:pk>/",
        views.GoalUpdate.as_view(template_name="data/crud/goal_update.html"),
        name="goal_update",
    ),
    # Media
    ## ebooks
    path("webpub/list/", views.WebpubList.as_view(template_name="data/crud/webpub_list.html"), name="webpub_list"),
    ### Reader
    path(
        "webpub/read/<int:pk>/",
        views.WebPubReadView.as_view(template_name="data/apps/webpub_read.html"),
        name="webpub_read",
    ),
    path("webpub/serve/<int:pk>/<path:resource_path>", views.WebPubServeView.as_view(), name="webpub_serve"),
    ## video subtitles
    path("video/list/", views.VideoList.as_view(template_name="data/crud/video_list.html"), name="video_list"),
    ### Media player
    path(
        "video/watch/<int:pk>/",
        views.VideoWatchView.as_view(template_name="data/apps/video_watch.html"),
        name="video_watch",
    ),
    # Settings and other user admin/management pages
    path(
        "coming_soon/",
        views.OnboardedTemplateView.as_view(template_name="data/settings/coming_soon.html"),
        name="coming_soon",
    ),
    path(
        "settings/", views.OnboardedTemplateView.as_view(template_name="data/settings/settings.html"), name="settings"
    ),
    path(
        "settings/profile",
        views.OnboardedTemplateView.as_view(template_name="data/settings/profile.html"),
        name="profile",
    ),
    path(
        "settings/reader",
        views.ReaderSettingsUpdate.as_view(template_name="data/settings/reader_settings.html"),
        name="reader_settings",
    ),
    path(
        "settings/media",
        views.MediaSettingsUpdate.as_view(template_name="data/settings/media_settings.html"),
        name="media_settings",
    ),
    path(
        "unsupported_browser/",
        views.TemplateView.as_view(template_name="data/settings/unsupported_browser.html"),
        name="unsupported_browser",
    ),
    path(
        "offline/",
        views.TemplateView.as_view(template_name="data/settings/offline.html"),
        name="offline",
    ),
    path(
        "initialisation/",
        views.InitialisationView.as_view(template_name="data/settings/initialisation.html"),
        name="initialisation",
    ),
    # FIXME: understand whether this must use dashes or can use underscores
    path(
        "change-password/",
        views.OnboardedTemplateView.as_view(template_name="registration/password_change_form.html"),
        name="change-password",
    ),
]

src/transcrobes/urls.py
# -*- coding: utf-8 -*-

from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

from utils import TranscrobesTokenObtainPairView, TranscrobesTokenRefreshView

from . import views

urlpatterns = [
    # Service worker
    path("sw.js", views.sw, name="serviceworker"),
    ## System paths
    path("admin/", admin.site.urls),
    # liveness
    path("hello", views.hello, name="hello"),
    # details of the pods
    path("pod_details", views.pod_details, name="pod_details"),
    # JWT auth
    path("api/token/", TranscrobesTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TranscrobesTokenRefreshView.as_view(), name="token_refresh"),
    # browsable rest api
    path("api-auth/", include("rest_framework.urls")),
    # metrics
    path("", include("django_prometheus.urls")),
    ## App paths
    # enricher
    path("enrich/", include("enrich.urls")),
    # Main app
    path("", include("data.urls")),
    # User management
    path("accounts/", include("registration.backends.default.urls")),
    path("accounts/", include("django.contrib.auth.urls")),  # new
    path("tos/", TemplateView.as_view(template_name="registration/tos.html"), name="tos"),
]

src/data/models.py
# -*- coding: utf-8 -*-

from __future__ import annotations

import csv
import io
import json
import logging
import os
from collections import Counter

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator, MaxValueValidator, MinValueValidator
from django.db import connection, models
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django_extensions.db.models import ActivatorModel, TimeStampedModel, TitleSlugDescriptionModel
from libgravatar import Gravatar
from upload_validator import FileTypeValidator

import stats
from enrich.models import BingAPILookup, BingAPITranslation
from enrich.translate.bing import BingTranslator
from ndutils import user_imports_path, user_resources_path
from zhhans_en.translate.ccc import ZHHANS_EN_CCCedictTranslator

from .validators import validate_file_size

MANIFEST_JSON = "manifest.json"
PARSE_JSON_SUFFIX = ".parse.json"
ENRICH_JSON_SUFFIX = ".enrich.json"
DATA_JS_SUFFIX = ".data.js"
SRT_EXTENTION = ".srt"
VTT_EXTENTION = ".vtt"
WEBVTT_FILE = "subtitles.vtt"


SIMPLIFIED_UTF8_ORD_MIN = 22909
SIMPLIFIED_UTF8_ORD_MAX = 40869

logger = logging.getLogger(__name__)

NONE = 0
REQUESTED = 1
PROCESSING = 2
FINISHED = 3
ERROR = 4

PROCESSING_STATUS = [
    (NONE, "None"),
    (REQUESTED, "Requested"),
    (PROCESSING, "Processing"),
    (FINISHED, "Finished"),
    (ERROR, "ERROR"),
]


class Card(models.Model):
    L2_GRAPH = 1
    L2_SOUND = 2
    L1_MEANING = 3

    CARD_TYPE = [
        (L2_GRAPH, "L2 written form"),  # JS GRAPH
        (L2_SOUND, "L2 sound form"),  # JS SOUND
        (L1_MEANING, "L1 meaning"),  # JS MEANING
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, help_text="Card owner")
    word = models.ForeignKey(BingAPILookup, on_delete=models.CASCADE)
    card_type = models.IntegerField(choices=CARD_TYPE, default=L2_GRAPH, help_text="Card type")
    interval = models.IntegerField(default=0, help_text="SM2 interval")
    repetition = models.IntegerField(default=0, help_text="SM2 repetition")
    efactor = models.FloatField(default=2.5, help_text="SM2 efactor")
    front = models.TextField(null=True, help_text="Override default definition cue")
    back = models.TextField(null=True, help_text="Override default definition expected response")
    due_date = models.DateTimeField(null=True)
    first_revision_date = models.DateTimeField(null=True)
    last_revision_date = models.DateTimeField(null=True)
    updated_at = models.DateTimeField(default=timezone.now)
    known = models.BooleanField(default=False, help_text="Learner believes they 'know' the word/cardtype")
    suspended = models.BooleanField(default=False, help_text="Don't revise the cardtype")
    deleted = models.BooleanField(default=False, help_text="Card has been deleted")


class Transcrober(models.Model):
    # FIXME: move this class to the transcrobes app
    DARK_MODE = "dark"
    LIGHT_MODE = "light"
    WHITE_MODE = "white"
    BLACK_MODE = "black"

    CONTENT_MODE = [
        (DARK_MODE, "Dark mode"),
        (LIGHT_MODE, "Light mode"),
        (WHITE_MODE, "White mode"),
        (BLACK_MODE, "Black mode"),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # TODO: this should probably be a OneToMany, so we can have users
    # who use the system for more than one language. KISS for the moment
    from_lang = models.CharField(max_length=20, default="zh-Hans")  # 20 is probably overkill
    to_lang = models.CharField(max_length=20, default="en")  # 20 is probably overkill

    # FIXME: this is pretty nasty, but while we are defaulting to from_lang="zh-Hans", why not!
    ds = f"{BingTranslator.SHORT_NAME},{ZHHANS_EN_CCCedictTranslator.SHORT_NAME},{BingTranslator.FALLBACK_SHORT_NAME}"
    dictionary_ordering = models.CharField(max_length=50, default=ds)

    default_segment = models.BooleanField(default=True, help_text="Segment texts by default")
    default_glossing = models.IntegerField(
        choices=stats.USER_GLOSSING_MODE,
        default=stats.GLOSSING_MODE_L1,
        help_text="Default gloss mode for platform-internal reading",
    )
    reading_mode = models.CharField(
        choices=CONTENT_MODE, max_length=100, default=DARK_MODE, help_text="Reading mode for platform-internal reading"
    )
    font_size_percent = models.IntegerField(
        validators=[MinValueValidator(30), MaxValueValidator(200)], default=100, help_text="Default font size percent"
    )
    subtitle_default_segment = models.BooleanField(default=True, help_text="Segment subtitles by default")
    subtitle_default_glossing = models.IntegerField(
        choices=stats.USER_GLOSSING_MODE,
        default=stats.GLOSSING_MODE_L1,
        help_text="Default gloss mode for platform-internal subtitles",
    )
    media_mode = models.CharField(
        choices=CONTENT_MODE, max_length=100, default=DARK_MODE, help_text="Video mode for platform-internal subtitles"
    )
    subtitle_box_width_percent = models.IntegerField(
        validators=[MinValueValidator(25), MaxValueValidator(100)],
        default=50,
        help_text="Default subtitle box width percent",
    )
    subtitle_font_size_percent = models.IntegerField(
        validators=[MinValueValidator(30), MaxValueValidator(250)],
        default=150,
        help_text="Default subtitle font size percent",
    )

    @staticmethod
    def get_absolute_url():
        return reverse("profile")

    def lang_pair(self):
        return f"{self.from_lang}:{self.to_lang}"

    def get_gravatar(self):
        return Gravatar(self.user.email).get_image()[5:]  # remove the 'http:'

    def get_full_name(self):
        full_name = f"{self.user.first_name} {self.user.last_name}"
        return full_name if full_name.strip() else self.user.username

    @cached_property
    def known_words(self):
        return set(
            BingAPILookup.objects.filter(userword__user=self.user, userword__is_known=True).values_list(
                "source_text", flat=True
            )
        )

    @cached_property
    def known_word_bases(self):
        # TODO: are these morphemes? sorta? it basically means "Chinese characters" but that's not very generic :-)
        return Counter("".join(self.known_words))

    def filter_known(self, words, min_morpheme_known_count=2, prefer_whole_known_words=True):
        if not words:
            return []  # or None?
        known = []
        whole_known_words = []
        for word in words:
            if word in self.known_words:
                if prefer_whole_known_words:
                    whole_known_words.append(word)
                else:
                    known.append(word)
            elif min_morpheme_known_count > 0:
                good = True
                for character in word:
                    if (
                        character not in self.known_word_bases
                        or self.known_word_bases[character] < min_morpheme_known_count
                    ):
                        good = False
                        break
                if good:
                    known.append(word)

        logger.debug(f"{whole_known_words + known=}")

        return whole_known_words + known

    def user_onboarded(self):
        ids = settings.USER_ONBOARDING_SURVEY_IDS
        return self.usersurvey_set.filter(survey__id__in=ids).count() == len(ids)


class DetailedModel(ActivatorModel, TimeStampedModel, TitleSlugDescriptionModel):
    def __str__(self):
        return f"{self.title}"

    class Meta:
        abstract = True


class DetailedProcessingModel(DetailedModel):
    class Meta:
        abstract = True

    def processing_status(self):
        if self.processing == FINISHED:
            return "Processed"

        if self.processing in [PROCESSING, REQUESTED]:
            return "Processing"

        if self.processing in [ERROR]:
            return "Error"

        return "None"


class Import(DetailedProcessingModel):
    VOCABULARY_ONLY = 1
    GRAMMAR_ONLY = 2
    VOCABULARY_GRAMMAR = 3
    PROCESS_TYPE = [
        (VOCABULARY_ONLY, "Vocabulary Only"),
        (GRAMMAR_ONLY, "Grammar Only"),
        (VOCABULARY_GRAMMAR, "Vocabulary and Grammar"),
    ]

    process_type = models.IntegerField(choices=PROCESS_TYPE, default=VOCABULARY_ONLY, help_text="What items to extract")
    user = models.ForeignKey(User, on_delete=models.CASCADE, help_text="Import owner")
    import_file = models.FileField(
        upload_to=user_imports_path,
        validators=[
            FileTypeValidator(
                allowed_types=["text/plain", "text/csv", "application/csv", "application/zip", "application/epub+zip"]
            ),
            FileExtensionValidator(allowed_extensions=["txt", "csv", "epub", "vtt", "srt"]),
            validate_file_size,
        ],
        help_text="File to import",
    )

    # TODO: think about alerting if the object modification time is too old and processed = null
    processing = models.IntegerField(choices=PROCESSING_STATUS, default=REQUESTED, help_text="Processing status")

    # TODO: maybe use a JSONField? It's JSON but we likely don't need the overhead in the db
    analysis = models.TextField(null=True)

    # shared, can be seen by others, and used as a template for creating their own versions
    shared = models.BooleanField(default=False, help_text="Allow others to see and use this import?")

    def processed(self):
        return self.processing == FINISHED

    def _relative_processed_path(self):
        return user_resources_path(self.user, os.path.basename(self.import_file.path))

    def processed_path(self):
        return os.path.join(settings.MEDIA_ROOT, self._relative_processed_path())

    def import_file_name(self):
        return os.path.basename(self.import_file.name)

src/data/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm

from data.models import Transcrober


class TranscroberForm(ModelForm):
    class Meta:
        model = Transcrober
        fields = ["default_glossing", "reading_mode", "font_size_percent"]

src/data/templates/data/crud/goal_create.html
<!-- templates/data/goal_create.html-->
{% extends 'data/base.html' %}
{% load widget_tweaks %}

{% block title %}Create Goal{% endblock %}

{% block content %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Create a new goal</h1>
</div>

<div class="row">
  <div class="col-xl-8 col-lg-7">
    <form class="user" method="post" enctype="multipart/form-data"> {% csrf_token %}
      {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
      {% endfor %}

      <div class="form-group form-error">
        <p>{% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
        </p>
      </div>
      <div class="form-group">
        {% render_field form.title class+="form-control form-control-user" aria-describedby="titleHelp" placeholder="Enter import title..." %}
      </div>
      {% if form.title.errors %}
      <div class="form-group form-error">
        {{ form.title.errors }}
      </div>
      {% endif %}

      <div class="form-group">
        {% render_field form.description rows="5" class+="form-control" aria-describedby="descriptionHelp" placeholder="Enter import description..." title="Goal description" %}
      </div>
      {% if form.description.errors %}
      <div class="form-group form-error">
        {{ form.description.errors }}
      </div>
      {% endif %}

      <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Active Status</label>
          {% render_field form.status class+="form-control" aria-describedby="statusHelp" placeholder="Status..." %}
        </div>
        <div class="col-sm-6">
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>List </label>
          {% render_field form.user_list class+="form-control" aria-describedby="userListHelp" placeholder="List..." %}
        </div>
        <div class="col-sm-6">
          <label>Parent</label>
          {% render_field form.parent class+="form-control" aria-describedby="parentHelp" placeholder="Parent..." %}
        </div>
      </div>

      <button class="btn btn-primary btn-user btn-block" type="submit">Create Goal</button>
    </form>
    <hr>
    <p><a href="{% url 'goal_list' %}" class="btn btn-primary btn-user btn-block"><i class="fas fa-arrow-left"></i> Goals</a></p>
  </div>
</div>

{% endblock %}

src/data/templates/data/crud/goal_detail.html
<!-- templates/data/goal_detail.html-->
{% extends 'data/base.html' %}
{% load static %}

{% block title %}Goal {{ goal.title }}{% endblock %}

{% block content %}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Goal {{ goal.title }} ({{ goal.id }})</h1>
</div>

<div class="card-body">
  <div class="row">
    <div class="col-lg-6">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-striped table-bordered">
              <thead>
                <tr><th>Field</th><th>Value</th></tr>
              </thead>
              <tbody>
                <tr><td>Id</td><td>{{ goal.id }}</td></tr>
                <tr><td>Is Active</td><td>{% if goal.status %} Active {% else %} Inactive {% endif %}</td></tr>
                <tr><td>Title</td><td>{{ goal.title }}</td></tr>
                <tr><td>Description</td><td>{{ goal.description|default:"" }}</td></tr>
                <tr><td>Priority</td><td>{{ goal.priority }}</td></tr>
                <tr><td>Created</td><td>{{ goal.created }}</td></tr>
                <tr><td>Modified</td><td>{{ goal.modified }}</td></tr>
                <tr><td>Associated List</td><td>{{ goal.user_list|default_if_none:"No List"}}</td></tr>
                <tr><td>Parent</td><td>{{ goal.parent|default:"No Parent" }}</td></tr>
                <tr><td>Children</td><td>{{ goal.sub_goal_names|join:"<br>"|default:"No Children" }}</td></tr>
                <tr><td>Progress</td><td>{% widthratio goal.get_progress_percent 1 100 %}%</td></tr>
              </tbody>
            </table>
          </div><!-- /.table-responsive -->
        </div><!-- /.panel-body -->
      </div><!-- /.panel -->
    </div><!-- /.col-lg-6 -->
  </div><!-- /.row -->
</div>

<div class="card-body">
  <div class="row">
    <div class="col-lg-6">
      <a class="btn btn-primary btn-user btn-block" href="{% url 'goal_update' pk=goal.id %}">Update this goal <i class="fas fa-arrow-right"></i></a>
    </div>
  </div>
</div>

<p><a href="{% url 'goal_list' %}" class="btn btn-primary btn-user btn-block"><i class="fas fa-arrow-left"></i> Goals</a></p>
<hr>

{% endblock %}

src/data/templates/data/crud/list_create.html
<!-- templates/data/list_create.html-->
{% extends 'data/base.html' %}
{% load widget_tweaks %}

{% block title %}Create List{% endblock %}

{% block content %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Create a new List</h1>
</div>

<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <p>When Transcrobes creates a list a number of analysis steps are required, which can take some time depending on how busy the system is. Please be patient while this happens - good things can take a little time! You can check the current status of your lists on the <a href="{% url 'list_list' %}">Lists page</a>.</p>
</div>


<div class="row">
  <div class="col-xl-8 col-lg-7">
    <form class="user" method="post" enctype="multipart/form-data"> {% csrf_token %}
      {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
      {% endfor %}

      <div class="form-group form-error">
        <p>{% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
        </p>
      </div>
      <div class="form-group">
        {% render_field form.title class+="form-control form-control-user" aria-describedby="titleHelp" placeholder="Enter list title..." %}
      </div>
      {% if form.title.errors %}
      <div class="form-group form-error">
        {{ form.title.errors }}
      </div>
      {% endif %}

      <div class="form-group">
        {% render_field form.description rows="5" class+="form-control" aria-describedby="descriptionHelp" placeholder="Enter list description..." title="List description" %}
      </div>
      {% if form.description.errors %}
      <div class="form-group form-error">
        {{ form.description.errors }}
      </div>
      {% endif %}

      <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>List active Status</label>
          {% render_field form.status class+="form-control" aria-describedby="statusHelp" placeholder="Status..." %}
        </div>
        <div class="col-sm-6">
          <label>Maximum size of the list (-1 for all)</label>
        {% render_field form.nb_to_take class+="form-control" aria-describedby="nbToTakeHelp" placeholder="Nb to take..." %}
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Source Import</label>
          {% render_field form.the_import class+="form-control" aria-describedby="userListHelp" placeholder="Import..." %}
        </div>
        <div class="col-sm-6">
          <label>Order by</label>
          {% render_field form.order_by class+="form-control" aria-describedby="parentHelp" placeholder="Order by..." %}
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label>Minimum document frequency (-1 for all)</label>
          {% render_field form.minimum_doc_frequency class+="form-control" aria-describedby="minimumDocFrequencyHelp" placeholder="Minimum frequency in document..." %}
        </div>
        <div class="col-sm-6">
          <label>Minimum absolute frequency (-1 for all)</label>
          {% render_field form.minimum_abs_frequency class+="form-control" aria-describedby="minimumAbsFrequencyHelp" placeholder="Minimum absolute frequency..." %}
        </div>
      </div>

      <div class="form-group row">
        {% comment %} <div class="col-sm-6 mb-3 mb-sm-0">
          <label for="id_add_notes">Add notes to spaced repetition (Anki)</label>
          {% render_field form.add_notes class+="" aria-describedby="addNotesHelp" placeholder="Add notes to spaced repetition..." %}
        </div> {% endcomment %}
        {% comment %} <div class="col-sm-6">
          <label for="id_only_dictionary_words">Only take items found in the dictionary</label>
          {% render_field form.only_dictionary_words class+="" aria-describedby="onlyDictionaryWordHelp" placeholder="Only take items if they appear in the default dictionary..." %}
        </div> {% endcomment %}
      </div>

      <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label for="id_shared">Share list with other learners (public list)</label>
          {% render_field form.shared class+="" aria-describedby="shareListHelp" placeholder="Public list..." %}
        </div>
        <div class="col-sm-6">
          <label for="id_words_are_known">Words are known</label>
          {% render_field form.words_are_known class+="" aria-describedby="wordsAreKnownHelp" placeholder="Words should be marked as known..." %}
        </div>
      </div>
      <button class="btn btn-primary btn-user btn-block" type="submit">Create List</button>
    </form>
    <hr>
    <p><a href="{% url 'list_list' %}" class="btn btn-primary btn-user btn-block"><i class="fas fa-arrow-left"></i> Lists</a></p>
  </div>
</div>

{% endblock %}

src/data/templates/data/crud/surveys.html
<!-- templates/data/surveys.html-->
{% extends 'data/base.html' %}

{% block title %}Research Surveys{% endblock %}

{% block content %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Surveys</h1>
</div>

{% if new_surveys %}
<div class="row">
  <!-- Unanswered Surveys -->
  <div class="col-xl-8 col-lg-7">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">New surveys</h6>
      </div>
      <!-- Card Body -->

      <div class="card-body">
        <ul>
          {% for survey in new_surveys %}
            <li><a href="{% url 'ui_survey_detail' survey_id=survey.id %}">{{ survey.title }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% if answered_surveys %}
<div class="row">
  <!-- Answered Surveys -->
  <div class="col-xl-8 col-lg-7">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Answered surveys</h6>
      </div>
      <!-- Card Body -->

      <div class="card-body">
        <ul>
          {% for survey in answered_surveys %}
            <li><a href="{% url 'ui_survey_detail' survey_id=survey.id %}">{{ survey.title }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% endblock %}