src/data/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.http.response import HttpResponse
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

import stats

from . import views
from .schema import schema

router = DefaultRouter()
router.register(r"surveys", views.SurveyViewSet)
router.register(r"usersurveys", views.UserSurveyViewSet)
router.register(r"users", views.UserViewSet)

# app_name = "data"  # namespacing has advantages but needs confusing extra config with DRF

urlpatterns = [
    path("api/", include(router.urls)),
    path("api/graphql", views.AsyncGraphQLView.as_view(schema=schema, graphiql=settings.DEBUG)),
]


def broadcast_test(request, pk):
    stats.KAFKA_PRODUCER.send("definitions", str(pk))
    return HttpResponse("hi here")


urlpatterns += [
    # testing
    # path("broadcast/<int:pk>/", broadcast_test, name="broadcast_test"),
    # path("test/", views.OnboardedTemplateView.as_view(template_name="data/test.html"), name="test"),
    # Service Worker template
    path(
        "sw.js",
        TemplateView.as_view(
            template_name="data/sw.js",
            content_type="application/javascript",
        ),
        name="sw",
    ),
    ## API
    path("precache_urls/", views.precache_urls, name="precache_urls"),
    path("user_event/", views.user_event, name="user_event"),
    # Backoffice
    path("", views.HomeView.as_view(template_name="data/home.html"), name="home"),
    ## Data entry
    path(
        "vocab/",
        views.OnboardedTemplateView.as_view(template_name="data/apps/notrobes.html"),
        name="notrobes",
    ),
    path(
        "vocab/list/",
        views.OnboardedTemplateView.as_view(template_name="data/apps/listrobes.html"),
        name="listrobes",
    ),
    ## Active Learning
    path(
        "vocab/review/",
        views.OnboardedTemplateView.as_view(template_name="data/apps/srsrobes.html"),
        name="srsrobes",
    ),
    ## Meta-knowledge management
    # survey.js surveys
    path(
        "survey/<int:survey_id>/",
        views.SurveyView.as_view(template_name="data/apps/survey_detail.html"),
        name="ui_survey_detail",
    ),
    path("surveys/", views.UserSurveysView.as_view(template_name="data/crud/surveys.html"), name="ui_survey_list"),
    # basic cruds
    path(
        "import/create/", views.ImportCreate.as_view(template_name="data/crud/import_create.html"), name="import_create"
    ),
    path("import/list/", views.ImportList.as_view(template_name="data/crud/import_list.html"), name="import_list"),
    path(
        "import/detail/<int:pk>/",
        views.ImportDetail.as_view(template_name="data/crud/import_detail.html"),
        name="import_detail",
    ),
    path(
        "list/create/<int:from_import>/",
        views.ListCreate.as_view(template_name="data/crud/list_create.html"),
        name="list_create",
    ),
    path("list/list/", views.ListList.as_view(template_name="data/crud/list_list.html"), name="list_list"),
    path(
        "list/detail/<int:pk>/",
        views.ListDetail.as_view(template_name="data/crud/list_detail.html"),
        name="list_detail",
    ),
    path(
        "goal/create/<int:from_list>/",
        views.GoalCreate.as_view(template_name="data/crud/goal_create.html"),
        name="goal_create",
    ),
    path("goal/list/", views.GoalList.as_view(template_name="data/crud/goal_list.html"), name="goal_list"),
    path(
        "goal/detail/<int:pk>/",
        views.GoalDetail.as_view(template_name="data/crud/goal_detail.html"),
        name="goal_detail",
    ),
    path(
        "goal/update/<int:pk>/",
        views.GoalUpdate.as_view(template_name="data/crud/goal_update.html"),
        name="goal_update",
    ),
    # Media
    ## ebooks
    path("webpub/list/", views.WebpubList.as_view(template_name="data/crud/webpub_list.html"), name="webpub_list"),
    ### Reader
    path(
        "webpub/read/<int:pk>/",
        views.WebPubReadView.as_view(template_name="data/apps/webpub_read.html"),
        name="webpub_read",
    ),
    path("webpub/serve/<int:pk>/<path:resource_path>", views.WebPubServeView.as_view(), name="webpub_serve"),
    ## video subtitles
    path("video/list/", views.VideoList.as_view(template_name="data/crud/video_list.html"), name="video_list"),
    ### Media player
    path(
        "video/watch/<int:pk>/",
        views.VideoWatchView.as_view(template_name="data/apps/video_watch.html"),
        name="video_watch",
    ),
    # Settings and other user admin/management pages
    path(
        "coming_soon/",
        views.OnboardedTemplateView.as_view(template_name="data/settings/coming_soon.html"),
        name="coming_soon",
    ),
    path(
        "settings/", views.OnboardedTemplateView.as_view(template_name="data/settings/settings.html"), name="settings"
    ),
    path(
        "settings/profile",
        views.OnboardedTemplateView.as_view(template_name="data/settings/profile.html"),
        name="profile",
    ),
    path(
        "settings/reader",
        views.ReaderSettingsUpdate.as_view(template_name="data/settings/reader_settings.html"),
        name="reader_settings",
    ),
    path(
        "settings/media",
        views.MediaSettingsUpdate.as_view(template_name="data/settings/media_settings.html"),
        name="media_settings",
    ),
    path(
        "unsupported_browser/",
        views.TemplateView.as_view(template_name="data/settings/unsupported_browser.html"),
        name="unsupported_browser",
    ),
    path(
        "offline/",
        views.TemplateView.as_view(template_name="data/settings/offline.html"),
        name="offline",
    ),
    path(
        "initialisation/",
        views.InitialisationView.as_view(template_name="data/settings/initialisation.html"),
        name="initialisation",
    ),
    # FIXME: understand whether this must use dashes or can use underscores
    path(
        "change-password/",
        views.OnboardedTemplateView.as_view(template_name="registration/password_change_form.html"),
        name="change-password",
    ),
]

src/transcrobes/urls.py
# -*- coding: utf-8 -*-

from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

from utils import TranscrobesTokenObtainPairView, TranscrobesTokenRefreshView

from . import views

urlpatterns = [
    # Service worker
    path("sw.js", views.sw, name="serviceworker"),
    ## System paths
    path("admin/", admin.site.urls),
    # liveness
    path("hello", views.hello, name="hello"),
    # details of the pods
    path("pod_details", views.pod_details, name="pod_details"),
    # JWT auth
    path("api/token/", TranscrobesTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TranscrobesTokenRefreshView.as_view(), name="token_refresh"),
    # browsable rest api
    path("api-auth/", include("rest_framework.urls")),
    # metrics
    path("", include("django_prometheus.urls")),
    ## App paths
    # enricher
    path("enrich/", include("enrich.urls")),
    # Main app
    path("", include("data.urls")),
    # User management
    path("accounts/", include("registration.backends.default.urls")),
    path("accounts/", include("django.contrib.auth.urls")),  # new
    path("tos/", TemplateView.as_view(template_name="registration/tos.html"), name="tos"),
]

src/data/models.py
# -*- coding: utf-8 -*-

from __future__ import annotations

import csv
import io
import json
import logging
import os
from collections import Counter

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator, MaxValueValidator, MinValueValidator
from django.db import connection, models
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django_extensions.db.models import ActivatorModel, TimeStampedModel, TitleSlugDescriptionModel
from libgravatar import Gravatar
from upload_validator import FileTypeValidator

import stats
from enrich.models import BingAPILookup, BingAPITranslation
from enrich.translate.bing import BingTranslator
from ndutils import user_imports_path, user_resources_path
from zhhans_en.translate.ccc import ZHHANS_EN_CCCedictTranslator

from .validators import validate_file_size

MANIFEST_JSON = "manifest.json"
PARSE_JSON_SUFFIX = ".parse.json"
ENRICH_JSON_SUFFIX = ".enrich.json"
DATA_JS_SUFFIX = ".data.js"
SRT_EXTENTION = ".srt"
VTT_EXTENTION = ".vtt"
WEBVTT_FILE = "subtitles.vtt"


SIMPLIFIED_UTF8_ORD_MIN = 22909
SIMPLIFIED_UTF8_ORD_MAX = 40869

logger = logging.getLogger(__name__)

NONE = 0
REQUESTED = 1
PROCESSING = 2
FINISHED = 3
ERROR = 4

PROCESSING_STATUS = [
    (NONE, "None"),
    (REQUESTED, "Requested"),
    (PROCESSING, "Processing"),
    (FINISHED, "Finished"),
    (ERROR, "ERROR"),
]


class Card(models.Model):
    L2_GRAPH = 1
    L2_SOUND = 2
    L1_MEANING = 3

    CARD_TYPE = [
        (L2_GRAPH, "L2 written form"),  # JS GRAPH
        (L2_SOUND, "L2 sound form"),  # JS SOUND
        (L1_MEANING, "L1 meaning"),  # JS MEANING
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, help_text="Card owner")
    word = models.ForeignKey(BingAPILookup, on_delete=models.CASCADE)
    card_type = models.IntegerField(choices=CARD_TYPE, default=L2_GRAPH, help_text="Card type")
    interval = models.IntegerField(default=0, help_text="SM2 interval")
    repetition = models.IntegerField(default=0, help_text="SM2 repetition")
    efactor = models.FloatField(default=2.5, help_text="SM2 efactor")
    front = models.TextField(null=True, help_text="Override default definition cue")
    back = models.TextField(null=True, help_text="Override default definition expected response")
    due_date = models.DateTimeField(null=True)
    first_revision_date = models.DateTimeField(null=True)
    last_revision_date = models.DateTimeField(null=True)
    updated_at = models.DateTimeField(default=timezone.now)
    known = models.BooleanField(default=False, help_text="Learner believes they 'know' the word/cardtype")
    suspended = models.BooleanField(default=False, help_text="Don't revise the cardtype")
    deleted = models.BooleanField(default=False, help_text="Card has been deleted")


class Transcrober(models.Model):
    # FIXME: move this class to the transcrobes app
    DARK_MODE = "dark"
    LIGHT_MODE = "light"
    WHITE_MODE = "white"
    BLACK_MODE = "black"

    CONTENT_MODE = [
        (DARK_MODE, "Dark mode"),
        (LIGHT_MODE, "Light mode"),
        (WHITE_MODE, "White mode"),
        (BLACK_MODE, "Black mode"),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # TODO: this should probably be a OneToMany, so we can have users
    # who use the system for more than one language. KISS for the moment
    from_lang = models.CharField(max_length=20, default="zh-Hans")  # 20 is probably overkill
    to_lang = models.CharField(max_length=20, default="en")  # 20 is probably overkill

    # FIXME: this is pretty nasty, but while we are defaulting to from_lang="zh-Hans", why not!
    ds = f"{BingTranslator.SHORT_NAME},{ZHHANS_EN_CCCedictTranslator.SHORT_NAME},{BingTranslator.FALLBACK_SHORT_NAME}"
    dictionary_ordering = models.CharField(max_length=50, default=ds)

    default_segment = models.BooleanField(default=True, help_text="Segment texts by default")
    default_glossing = models.IntegerField(
        choices=stats.USER_GLOSSING_MODE,
        default=stats.GLOSSING_MODE_L1,
        help_text="Default gloss mode for platform-internal reading",
    )
    reading_mode = models.CharField(
        choices=CONTENT_MODE, max_length=100, default=DARK_MODE, help_text="Reading mode for platform-internal reading"
    )
    font_size_percent = models.IntegerField(
        validators=[MinValueValidator(30), MaxValueValidator(200)], default=100, help_text="Default font size percent"
    )
    subtitle_default_segment = models.BooleanField(default=True, help_text="Segment subtitles by default")
    subtitle_default_glossing = models.IntegerField(
        choices=stats.USER_GLOSSING_MODE,
        default=stats.GLOSSING_MODE_L1,
        help_text="Default gloss mode for platform-internal subtitles",
    )
    media_mode = models.CharField(
        choices=CONTENT_MODE, max_length=100, default=DARK_MODE, help_text="Video mode for platform-internal subtitles"
    )
    subtitle_box_width_percent = models.IntegerField(
        validators=[MinValueValidator(25), MaxValueValidator(100)],
        default=50,
        help_text="Default subtitle box width percent",
    )
    subtitle_font_size_percent = models.IntegerField(
        validators=[MinValueValidator(30), MaxValueValidator(250)],
        default=150,
        help_text="Default subtitle font size percent",
    )

    @staticmethod
    def get_absolute_url():
        return reverse("profile")

    def lang_pair(self):
        return f"{self.from_lang}:{self.to_lang}"

    def get_gravatar(self):
        return Gravatar(self.user.email).get_image()[5:]  # remove the 'http:'

    def get_full_name(self):
        full_name = f"{self.user.first_name} {self.user.last_name}"
        return full_name if full_name.strip() else self.user.username

    @cached_property
    def known_words(self):
        return set(
            BingAPILookup.objects.filter(userword__user=self.user, userword__is_known=True).values_list(
                "source_text", flat=True
            )
        )

    @cached_property
    def known_word_bases(self):
        # TODO: are these morphemes? sorta? it basically means "Chinese characters" but that's not very generic :-)
        return Counter("".join(self.known_words))

    def filter_known(self, words, min_morpheme_known_count=2, prefer_whole_known_words=True):
        if not words:
            return []  # or None?
        known = []
        whole_known_words = []
        for word in words:
            if word in self.known_words:
                if prefer_whole_known_words:
                    whole_known_words.append(word)
                else:
                    known.append(word)
            elif min_morpheme_known_count > 0:
                good = True
                for character in word:
                    if (
                        character not in self.known_word_bases
                        or self.known_word_bases[character] < min_morpheme_known_count
                    ):
                        good = False
                        break
                if good:
                    known.append(word)

        logger.debug(f"{whole_known_words + known=}")

        return whole_known_words + known

    def user_onboarded(self):
        ids = settings.USER_ONBOARDING_SURVEY_IDS
        return self.usersurvey_set.filter(survey__id__in=ids).count() == len(ids)


class DetailedModel(ActivatorModel, TimeStampedModel, TitleSlugDescriptionModel):
    def __str__(self):
        return f"{self.title}"

    class Meta:
        abstract = True


class DetailedProcessingModel(DetailedModel):
    class Meta:
        abstract = True

    def processing_status(self):
        if self.processing == FINISHED:
            return "Processed"

        if self.processing in [PROCESSING, REQUESTED]:
            return "Processing"

        if self.processing in [ERROR]:
            return "Error"

        return "None"


class Import(DetailedProcessingModel):
    VOCABULARY_ONLY = 1
    GRAMMAR_ONLY = 2
    VOCABULARY_GRAMMAR = 3
    PROCESS_TYPE = [
        (VOCABULARY_ONLY, "Vocabulary Only"),
        (GRAMMAR_ONLY, "Grammar Only"),
        (VOCABULARY_GRAMMAR, "Vocabulary and Grammar"),
    ]

    process_type = models.IntegerField(choices=PROCESS_TYPE, default=VOCABULARY_ONLY, help_text="What items to extract")
    user = models.ForeignKey(User, on_delete=models.CASCADE, help_text="Import owner")
    import_file = models.FileField(
        upload_to=user_imports_path,
        validators=[
            FileTypeValidator(
                allowed_types=["text/plain", "text/csv", "application/csv", "application/zip", "application/epub+zip"]
            ),
            FileExtensionValidator(allowed_extensions=["txt", "csv", "epub", "vtt", "srt"]),
            validate_file_size,
        ],
        help_text="File to import",
    )

    # TODO: think about alerting if the object modification time is too old and processed = null
    processing = models.IntegerField(choices=PROCESSING_STATUS, default=REQUESTED, help_text="Processing status")

    # TODO: maybe use a JSONField? It's JSON but we likely don't need the overhead in the db
    analysis = models.TextField(null=True)

    # shared, can be seen by others, and used as a template for creating their own versions
    shared = models.BooleanField(default=False, help_text="Allow others to see and use this import?")

    def processed(self):
        return self.processing == FINISHED

    def _relative_processed_path(self):
        return user_resources_path(self.user, os.path.basename(self.import_file.path))

    def processed_path(self):
        return os.path.join(settings.MEDIA_ROOT, self._relative_processed_path())

    def import_file_name(self):
        return os.path.basename(self.import_file.name)

src/data/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm

from data.models import Transcrober


class TranscroberForm(ModelForm):
    class Meta:
        model = Transcrober
        fields = ["default_glossing", "reading_mode", "font_size_percent"]

src/data/templates/data/settings/coming_soon.html
<!-- templates/data/coming_soon.html-->
{% extends 'data/base.html' %}
{% load static %}

{% block title %}Coming soon{% endblock %}

{% block content %}
<div id="root" />
  <!-- Begin Page Content -->
  <div class="container-fluid">
    <div class="text-center">
      <h1 class="mb-5" data-text="Coming Soon" style="text-align:center">Coming Soon</h1>
      <p class="lead text-gray-800 mb-5">We're frantically developing new stuff for you!</p>
      <p class="text-gray-500 mb-0">It looks like you found a page we haven't made available yet... But it'll be here soon!</p>
      <a href="{% url 'home' %}">&larr; Back to Dashboard</a>
    </div>

  </div>
  <!-- /.container-fluid -->
</div>
{% endblock %}

src/data/templates/data/settings/media_settings.html
<!-- templates/data/media_settings.html-->
{% extends 'data/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Media player settings{% endblock %}

{% block content %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Media player settings</h1>
</div>

<div class="row">
  <div class="col-xl-8 col-lg-7">
    <form class="user" method="post" enctype="multipart/form-data"> {% csrf_token %}
      {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
      {% endfor %}

      {% if messages %}
      <div class="form-group">
        <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}

      {% if form.non_field_errors %}
      <div class="form-group form-error">
        <p>
        {{ form.non_field_errors }}
        </p>
      </div>
      {% endif %}

      <div class="form-group">
        <label for="id_subtitle_default_glossing">Glossing type</label>
        {% render_field form.subtitle_default_glossing class+="form-control" aria-describedby="subtitleGlossingHelp" placeholder="Enter subtitle glossing..." %}
      </div>
      {% if form.subtitle_default_glossing.errors %}
      <div class="form-group form-error">
        {{ form.subtitle_default_glossing.errors }}
      </div>
      {% endif %}

      <div class="form-group">
        <label for="id_subtitle_default_segment">Segment texts into words</label>
        {% render_field form.subtitle_default_segment class+="" aria-describedby="subtitleSegmentationHelp" placeholder="Enter subtitle segmentation..." %}
      </div>
      {% if form.subtitle_default_segment.errors %}
      <div class="form-group form-error">
        {{ form.subtitle_default_segment.errors }}
      </div>
      {% endif %}

      <div class="form-group">
        <label for="id_media_mode">Media mode</label>
        {% render_field form.media_mode class+="form-control" aria-describedby="mediaModeHelp" placeholder="Select media mode..." title="Media mode" %}
      </div>
      {% if form.media_mode.errors %}
      <div class="form-group form-error">
        {{ form.media_mode.errors }}
      </div>
      {% endif %}

      <div class="form-group">
        <label for="id_subtitle_box_width_percent">Subtitle box max width (in %)</label>
        {% render_field form.subtitle_box_width_percent class+="form-control" aria-describedby="subBoxWidthPercentHelp" placeholder="Subtitle box width..." title="Subtitles box width percent" %}
      </div>
      {% if form.subtitle_box_width_percent.errors %}
      <div class="form-group form-error">
        {{ form.subtitle_box_width_percent.errors }}
      </div>
      {% endif %}

      <div class="form-group">
        <label for="id_subtitle_font_size_percent">Subtitle font size (in %)</label>
        {% render_field form.subtitle_font_size_percent class+="form-control" aria-describedby="fontSizePercentHelp" placeholder="Font size..." title="Font size percent" %}
      </div>
      {% if form.subtitle_font_size_percent.errors %}
      <div class="form-group form-error">
        {{ form.subtitle_font_size_percent.errors }}
      </div>
      {% endif %}

      <button class="btn btn-primary btn-user btn-block" type="submit">Update</button>
    </form>
    <hr>
    <p><a href="{% url 'settings' %}" class="btn btn-primary btn-user btn-block"><i class="fas fa-arrow-left"></i> Settings</a></p>
  </div>
</div>

{% endblock %}

src/data/templates/data/settings/offline.html
<!-- templates/settings/offline.html -->
{% extends 'data/unauth_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Offline{% endblock %}

{% block content %}
<!-- Outer Row -->
<div class="row justify-content-center">
  <div class="col-xl-10 col-lg-12 col-md-9">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
          <div class="col-lg-6">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Offline</h1>
                <p>Unfortunately, it looks like there is no internet connection or there is a problem with the server. Most of Transcrobes can function properly offline but certain pages and services require an active connection. Please try connecting to a network or continue learning with the offline functionality!</p>
                <div style="display:flex; justify-content: center; padding-bottom: 2em">
                  <button style="width: 90%" onclick="window.history.back()" class="btn btn-primary btn-user btn-block"><i class="fas fa-arrow-left"></i> Return to the Dashboard</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/data/templates/data/settings/profile.html
<!-- templates/data/profile.html-->
{% extends 'data/base.html' %}
{% load widget_tweaks %}

{% block title %}Update Learner Profile{% endblock %}

{% block content %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Update Learner Profile</h1>
</div>

<div class="row">
  <div class="col-xl-8 col-lg-7">
    <p class="mb-4">If you would like to stop using the platform, you have a number of options:
    <ul>
      <li>You can simply not use the platform any more and uninstall any client applications, like the Brocrobes Chrome Extension, this website, etc. In this case your existing data will continue to be used in the active university research programme. You can always start using the platform again if you change your mind.</li>
      <li>You can ask for your account to be completely deactivated by contacting Anton MELSER, anton.melser@my.cityu.edu.hk. In this case your existing data will continue to be used in the active university research programme. You can always start using the platform again if you change your mind by writing to Anton MELSER and requesting your account be reactivated.</li>
      <li>You can ask for your account to be completely deleted by contacting Anton MELSER, anton.melser@my.cityu.edu.hk, including any existing data generated. This is the nuclear option, and all data will be irreversibly deleted. Except in very exceptional circumstances this will mean the end of your participation in the research, though you are obviously more than welcome to download and run the system yourself on your own resources!</li>
    </ul>
    </p>

    <hr>
    <p><a href="{% url 'settings' %}" class="btn btn-primary btn-user btn-block"><i class="fas fa-arrow-left"></i> Settings</a></p>
  </div>
</div>
{% endblock %}

src/data/templates/data/settings/reader_settings.html
<!-- templates/data/reader_settings.html-->
{% extends 'data/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Reader settings{% endblock %}

{% block content %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Reader settings</h1>
</div>

<div class="row">
  <div class="col-xl-8 col-lg-7">
    <form class="user" method="post" enctype="multipart/form-data"> {% csrf_token %}
      {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
      {% endfor %}

      {% if messages %}
      <div class="form-group">
        <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}

      {% if form.non_field_errors %}
      <div class="form-group form-error">
        <p>
        {{ form.non_field_errors }}
        </p>
      </div>
      {% endif %}

      <div class="form-group">
        <label for="id_default_glossing">Glossing type</label>
        {% render_field form.default_glossing class+="form-control" aria-describedby="glossingHelp" placeholder="Enter glossing..." %}
      </div>
      {% if form.default_glossing.errors %}
      <div class="form-group form-error">
        {{ form.default_glossing.errors }}
      </div>
      {% endif %}

      <div class="form-group">
        <label for="id_default_segment">Segment texts into words</label>
        {% render_field form.default_segment class+="" aria-describedby="segmentationHelp" placeholder="Enter segmentation..." %}
      </div>
      {% if form.default_segment.errors %}
      <div class="form-group form-error">
        {{ form.default_segment.errors }}
      </div>
      {% endif %}

      <div class="form-group">
        <label for="id_reading_mode">Reading mode</label>
        {% render_field form.reading_mode class+="form-control" aria-describedby="readingModeHelp" placeholder="Select reading mode..." title="Reading mode" %}
      </div>
      {% if form.reading_mode.errors %}
      <div class="form-group form-error">
        {{ form.reading_mode.errors }}
      </div>
      {% endif %}

      <div class="form-group">
        <label for="id_font_size_percent">Font size (in %)</label>
        {% render_field form.font_size_percent class+="form-control" aria-describedby="fontSizePercentHelp" placeholder="Font size..." title="Font size percent" %}
      </div>
      {% if form.font_size_percent.errors %}
      <div class="form-group form-error">
        {{ form.font_size_percent.errors }}
      </div>
      {% endif %}

      <button class="btn btn-primary btn-user btn-block" type="submit">Update</button>
    </form>
    <hr>
    <p><a href="{% url 'settings' %}" class="btn btn-primary btn-user btn-block"><i class="fas fa-arrow-left"></i> Settings</a></p>
  </div>
</div>

{% endblock %}


{% block extrajs %}
{% endblock %}